# Generated by Django 4.0.6 on 2022-08-02 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='following',
            new_name='followings',
        ),
    ]
